language: node_js
node_js:
  - "8"
before_install:
  - npm install -g unitejs-cli
  - npm install -g gulp
  - unite configure --profile=AngularTypeScript --title="Electron QuickStart" --packageName=unitejs-electron-quickstart --outputDirectory=./
  - unite platform --operation=add --platformName=Electron
  - cd www
install:
  - npm install
script: 
  - gulp build || travis_terminate 1
  - gulp unit || travis_terminate 1
  - gulp e2e-install --drivers=chrome@2.33 || travis_terminate 1
  - gulp e2e || travis_terminate 1
  - gulp platform-electron-dev || travis_terminate 1
  - gulp build --buildConfiguration=prod || travis_terminate 1
  - gulp e2e || travis_terminate 1
  - gulp platform-electron-package --buildConfiguration=prod || travis_terminate 1
